env_url:
  travel_insurance_link: 'https://www.bolttech.co.th/en/inbound-travel-insurance'
  profile:
    - travel_insurance_url
    - teste
  password2: password
teste12312:
  name: admin
  password1: password
  user2: teacher
  profile:
    - teste2
  password2: password